@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
User -> Main: Start app
Main -> Controller: Calls controller
Controller -> ConsoleUI: Application started
ConsoleUI -> User: Welcome message
ConsoleUI -> User: App menu
User ->o Controller: Chooses option
Controller ->o Service: Calls method
Service o<->o Database: Data

Service o<->o WeatherAPI: Data
Service ->o Controller: Returns data
Controller ->o ConsoleUI: Passes data
ConsoleUI ->o User: Shows to user
ConsoleUI ->o User: What do you want to do next?
@enduml